import urllib.request, json

TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjbnZxaml2YmJ5emV1cmJvbXB2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MDg1MjM1NSwiZXhwIjoyMDk2NDI4MzU1fQ.-TSORpRQBwvoh91eD0jfNDi0pDXuh-tG5wa--pBy1D4"
BASE = "https://kcnvqjivbbyzeurbompv.supabase.co/rest/v1"

def post(table, data):
    body = json.dumps(data).encode("utf-8")
    req = urllib.request.Request(f"{BASE}/{table}", data=body, headers={
        "apikey": TOKEN, "Authorization": f"Bearer {TOKEN}",
        "Content-Type": "application/json", "Prefer": "resolution=ignore-duplicates",
    }, method="POST")
    try:
        with urllib.request.urlopen(req) as r: return r.status
    except urllib.error.HTTPError as e: return f"ERR {e.code}: {e.read().decode()[:200]}"

# ═══════════════════════════════════════════════════════════════════
# BA1 LESSONS
# ═══════════════════════════════════════════════════════════════════

ba1_lessons = [
  {
    "id":"ba100000-0001-0001-0000-000000000000","module_id":"ba100000-0001-0000-0000-000000000000",
    "title":"Supply, Demand and Market Equilibrium","order_index":1,"xp_reward":50,"estimated_minutes":8,"is_published":True,
    "content":[
      {"type":"intro","emoji":"⚖️","heading":"Supply, Demand and Market Equilibrium","body":"Markets coordinate millions of individual decisions through the price mechanism. Understanding how supply and demand interact explains how prices are determined and how markets reach equilibrium."},
      {"type":"explanation","heading":"The Law of Demand","body":"As the price of a good rises, the quantity demanded falls (ceteris paribus). This inverse relationship gives the demand curve its downward slope.","key_terms":[{"term":"Demand","definition":"The quantity buyers are willing and able to purchase at each price."},{"term":"Ceteris paribus","definition":"All other factors held constant."},{"term":"Substitute goods","definition":"Goods that can replace each other (e.g. tea and coffee)."},{"term":"Complementary goods","definition":"Goods used together (e.g. cars and petrol)."}]},
      {"type":"explanation","heading":"Shifts in the Demand Curve","body":"A change in price causes a movement along the demand curve. A change in any other factor shifts the entire curve. Factors shifting demand: income, prices of substitutes/complements, consumer tastes, population, expectations.","key_terms":[{"term":"Movement along","definition":"Caused by a price change."},{"term":"Shift of curve","definition":"Caused by non-price factors such as income, tastes, or related goods prices."}]},
      {"type":"explanation","heading":"The Law of Supply","body":"As the price of a good rises, the quantity supplied increases (ceteris paribus). Producers supply more at higher prices because it becomes more profitable.","key_terms":[{"term":"Supply","definition":"The quantity sellers are willing and able to offer at each price."},{"term":"Factors shifting supply","definition":"Input costs, technology, number of producers, government subsidies/taxes."}]},
      {"type":"worked_example","heading":"Finding Market Equilibrium","steps":["At equilibrium: quantity demanded = quantity supplied.","Example: Qd = 100 - 5P and Qs = 20 + 3P","Set equal: 100 - 5P = 20 + 3P","80 = 8P so P* = £10","Substitute back: Q* = 100 - 5(10) = 50 units","Equilibrium: price = £10, quantity = 50 units."]},
      {"type":"explanation","heading":"Excess Demand and Excess Supply","body":"If price is below equilibrium, Qd > Qs (shortage) and price rises. If above equilibrium, Qs > Qd (surplus) and price falls. The market self-corrects.","key_terms":[{"term":"Excess demand (shortage)","definition":"Qd > Qs — price rises."},{"term":"Excess supply (surplus)","definition":"Qs > Qd — price falls."},{"term":"Price mechanism","definition":"The system by which prices adjust to clear markets."}]}
    ]
  },
  {
    "id":"ba100000-0001-0002-0000-000000000000","module_id":"ba100000-0001-0000-0000-000000000000",
    "title":"Price Elasticity of Demand and Supply","order_index":2,"xp_reward":50,"estimated_minutes":8,"is_published":True,
    "content":[
      {"type":"intro","emoji":"📐","heading":"Price Elasticity of Demand and Supply","body":"Elasticity measures the responsiveness of quantity demanded or supplied to a change in price. Essential for pricing decisions and assessing the impact of taxation."},
      {"type":"worked_example","heading":"Calculating Price Elasticity of Demand (PED)","steps":["PED = % change in quantity demanded / % change in price","PED is always negative (inverse relationship).","Example: Price rises from £10 to £12 (+20%); quantity falls from 100 to 85 units (-15%).","PED = -15% / 20% = -0.75","If |PED| < 1, demand is inelastic (quantity relatively unresponsive to price)."]},
      {"type":"table","heading":"Interpreting PED Values","headers":["|PED| value","Description","Implication for revenue"],"rows":[["> 1","Elastic: % change in Qd > % change in P","Price rise means revenue falls"],["= 1","Unit elastic: % change in Qd = % change in P","Price change means no revenue change"],["< 1","Inelastic: % change in Qd < % change in P","Price rise means revenue increases"],["= 0","Perfectly inelastic","Quantity fixed regardless of price"],["= infinity","Perfectly elastic","Any price rise means zero demand"]]},
      {"type":"explanation","heading":"Factors Affecting PED","body":"Several factors determine whether demand is elastic or inelastic.","key_terms":[{"term":"Number of substitutes","definition":"More substitutes means more elastic demand."},{"term":"Necessity vs luxury","definition":"Necessities tend to be inelastic."},{"term":"Proportion of income","definition":"Higher proportion spent means more elastic."},{"term":"Time period","definition":"Demand becomes more elastic over time as consumers adjust."}]},
      {"type":"worked_example","heading":"Price Elasticity of Supply (PES)","steps":["PES = % change in quantity supplied / % change in price","PES is always positive.","Example: Price rises from £20 to £25 (+25%); Qs rises from 200 to 220 (+10%).","PES = 10% / 25% = 0.4 — inelastic supply.","Supply is inelastic when: spare capacity is lacking, production period is long, inputs are fixed."]},
      {"type":"explanation","heading":"Income Elasticity of Demand (YED)","body":"YED = % change in Qd / % change in income. Normal goods: YED > 0. Inferior goods: YED < 0. Luxury goods: YED > 1.","key_terms":[{"term":"Normal good","definition":"YED > 0: demand rises with income."},{"term":"Inferior good","definition":"YED < 0: demand falls as income rises."},{"term":"Luxury good","definition":"YED > 1: income elastic."}]}
    ]
  },
  {
    "id":"ba100000-0001-0003-0000-000000000000","module_id":"ba100000-0001-0000-0000-000000000000",
    "title":"Market Structures","order_index":3,"xp_reward":50,"estimated_minutes":10,"is_published":True,
    "content":[
      {"type":"intro","emoji":"🏭","heading":"Market Structures","body":"A market structure describes the competitive environment in which firms operate. Structure affects pricing power, output decisions, profit levels, and efficiency. CIMA BA1 covers four main structures."},
      {"type":"table","heading":"Overview of Market Structures","headers":["Feature","Perfect Competition","Monopolistic Competition","Oligopoly","Monopoly"],"rows":[["Number of firms","Very many","Many","Few","One"],["Product","Identical","Differentiated","Similar or differentiated","Unique"],["Barriers to entry","None","Low","High","Very high"],["Price setting","Price taker","Some power","Interdependent","Price maker"],["Long-run profit","Normal only","Normal only","Supernormal possible","Supernormal possible"],["Example","Agricultural commodities","Restaurants","Supermarkets, airlines","Utilities"]]},
      {"type":"explanation","heading":"Perfect Competition","body":"Firms are price takers. Any supernormal profit is competed away by free entry. Allocatively and productively efficient.","key_terms":[{"term":"Price taker","definition":"Firm accepts the market price; no power to set it."},{"term":"Normal profit","definition":"The minimum return needed to keep the firm in business."},{"term":"Supernormal profit","definition":"Profit above normal; attracts new entrants."}]},
      {"type":"explanation","heading":"Monopoly","body":"The sole supplier acts as a price maker. High barriers to entry protect supernormal profits. Monopolists can price discriminate.","key_terms":[{"term":"Price maker","definition":"Firm sets its own price and faces a downward-sloping demand curve."},{"term":"Barriers to entry","definition":"Legal (patents, licences), economies of scale, ownership of scarce resources."},{"term":"Price discrimination","definition":"Charging different prices to different customer groups."},{"term":"Dead-weight loss","definition":"Welfare lost because output is below the competitive level."}]},
      {"type":"explanation","heading":"Oligopoly and Game Theory","body":"A small number of large, interdependent firms dominate the market. Each firm must consider rivals' reactions. The Prisoners' Dilemma illustrates why firms may not collude even when it would benefit both.","key_terms":[{"term":"Interdependence","definition":"Each firm must consider rivals' reactions before acting."},{"term":"Collusion","definition":"Agreement to fix prices or share markets (illegal cartel)."},{"term":"Kinked demand curve","definition":"Prices tend to be sticky in oligopolies."}]}
    ]
  },
  {
    "id":"ba100000-0002-0001-0000-000000000000","module_id":"ba100000-0002-0000-0000-000000000000",
    "title":"GDP, Business Cycles and Economic Growth","order_index":1,"xp_reward":50,"estimated_minutes":8,"is_published":True,
    "content":[
      {"type":"intro","emoji":"📊","heading":"GDP, Business Cycles and Economic Growth","body":"Gross Domestic Product (GDP) is the main measure of an economy's output. Understanding how GDP is measured and how it fluctuates over the business cycle is fundamental to macroeconomic analysis."},
      {"type":"explanation","heading":"Measuring GDP","body":"GDP can be measured three ways, each giving the same result in theory. Real GDP adjusts for inflation.","key_terms":[{"term":"Expenditure approach","definition":"GDP = C + I + G + (X - M)"},{"term":"Income approach","definition":"Sum of all factor incomes (wages, profits, rent, interest)."},{"term":"Output approach","definition":"Sum of value added at each stage of production."},{"term":"Real GDP","definition":"Adjusted for inflation — measures actual volume of output."}]},
      {"type":"table","heading":"Phases of the Business Cycle","headers":["Phase","Characteristics","Policy response"],"rows":[["Expansion / Boom","Rising GDP, low unemployment, rising prices","Contractionary policy"],["Peak","Maximum output, full employment, inflationary pressure","Tighten monetary policy"],["Contraction / Recession","Falling GDP (2+ quarters), rising unemployment","Expansionary stimulus"],["Trough","Minimum output, highest unemployment","Fiscal stimulus, low interest rates"]]},
      {"type":"explanation","heading":"Economic Growth and the Multiplier","body":"The Keynesian multiplier shows how an initial change in spending leads to a larger change in national income.","key_terms":[{"term":"MPC","definition":"Marginal Propensity to Consume: fraction of extra income spent on consumption."},{"term":"MPS","definition":"Marginal Propensity to Save: fraction of extra income saved. MPC + MPS = 1."},{"term":"Multiplier","definition":"1 / (1 - MPC) = 1 / MPS"},{"term":"Injection","definition":"Government spending, investment, exports — add to circular flow."},{"term":"Withdrawal","definition":"Saving, taxation, imports — remove from circular flow."}]}
    ]
  },
  {
    "id":"ba100000-0002-0002-0000-000000000000","module_id":"ba100000-0002-0000-0000-000000000000",
    "title":"Inflation and Unemployment","order_index":2,"xp_reward":50,"estimated_minutes":8,"is_published":True,
    "content":[
      {"type":"intro","emoji":"💹","heading":"Inflation and Unemployment","body":"Inflation and unemployment are two of the most closely watched macroeconomic indicators. Governments and central banks aim to keep both low and stable."},
      {"type":"explanation","heading":"Measuring and Causes of Inflation","body":"Inflation is measured by the Consumer Prices Index (CPI) or Retail Prices Index (RPI).","key_terms":[{"term":"CPI","definition":"Measures the average change in prices of a basket of goods and services."},{"term":"Demand-pull inflation","definition":"Caused by excess aggregate demand — too much money chasing too few goods."},{"term":"Cost-push inflation","definition":"Caused by rising production costs passed on as higher prices."},{"term":"Hyperinflation","definition":"Extremely rapid price rises that destroy confidence in money."}]},
      {"type":"explanation","heading":"Effects of Inflation","body":"Moderate inflation (around 2%) is healthy. High or volatile inflation creates economic uncertainty.","key_terms":[{"term":"Redistributive effects","definition":"Debtors gain (real value of debt falls); creditors lose."},{"term":"Competitiveness","definition":"High domestic inflation makes exports more expensive."},{"term":"Menu costs","definition":"Cost of updating prices frequently."},{"term":"Shoe-leather costs","definition":"Time and effort wasted managing cash when money loses value."}]},
      {"type":"table","heading":"Types of Unemployment","headers":["Type","Cause","Policy solution"],"rows":[["Frictional","Transition between jobs","Better job information"],["Structural","Long-term industry decline; skill mismatch","Retraining, regional investment"],["Cyclical","Insufficient aggregate demand","Fiscal or monetary stimulus"],["Seasonal","Demand fluctuates seasonally","Benefits system, flexible contracts"]]},
      {"type":"explanation","heading":"The Phillips Curve","body":"The short-run Phillips Curve shows a trade-off: lower unemployment tends to mean higher inflation. In the long run, this breaks down as expectations adjust.","key_terms":[{"term":"Phillips Curve","definition":"Inverse short-run relationship between inflation and unemployment."},{"term":"Natural Rate of Unemployment (NRU)","definition":"Unemployment when the labour market is in equilibrium."}]}
    ]
  },
  {
    "id":"ba100000-0002-0003-0000-000000000000","module_id":"ba100000-0002-0000-0000-000000000000",
    "title":"Fiscal and Monetary Policy","order_index":3,"xp_reward":50,"estimated_minutes":8,"is_published":True,
    "content":[
      {"type":"intro","emoji":"🏦","heading":"Fiscal and Monetary Policy","body":"Governments and central banks use fiscal and monetary policy to manage the macroeconomy — aiming for stable growth, low inflation, and high employment."},
      {"type":"explanation","heading":"Fiscal Policy","body":"Government decisions on taxation and public spending. Directly affects aggregate demand.","key_terms":[{"term":"Expansionary fiscal policy","definition":"Increase spending or cut taxes to stimulate demand (used in recession)."},{"term":"Contractionary fiscal policy","definition":"Cut spending or raise taxes to reduce demand (used to control inflation)."},{"term":"Budget deficit","definition":"Government spending exceeds tax revenue."},{"term":"Automatic stabilisers","definition":"Tax/benefit systems that automatically dampen economic cycles."}]},
      {"type":"explanation","heading":"Monetary Policy","body":"Controlled by the central bank (Bank of England). The Bank's primary objective is to maintain inflation at 2% CPI.","key_terms":[{"term":"Bank Rate","definition":"The interest rate set by the Bank of England; affects all other rates."},{"term":"Tight monetary policy","definition":"Raise interest rates to reduce borrowing/spending and lower inflation."},{"term":"Loose monetary policy","definition":"Cut interest rates to encourage borrowing and stimulate growth."},{"term":"Quantitative Easing (QE)","definition":"Central bank creates money to buy assets; increases money supply."}]},
      {"type":"table","heading":"Comparing Fiscal and Monetary Policy","headers":["Feature","Fiscal Policy","Monetary Policy"],"rows":[["Controlled by","Government (Chancellor)","Central Bank (Bank of England)"],["Main tools","Spending, taxation","Interest rates, QE"],["Speed","Slow (requires legislation)","Faster (MPC meets monthly)"],["Political influence","High","Low (independent central bank)"]]},
      {"type":"explanation","heading":"Supply-Side Policies","body":"Aim to increase productive capacity rather than managing demand. Address long-run growth.","key_terms":[{"term":"Labour market reforms","definition":"Improve training, cut benefits to increase incentives to work."},{"term":"Privatisation","definition":"Transfer state-owned industries to private sector for efficiency."},{"term":"Deregulation","definition":"Remove barriers to entry and red tape."}]}
    ]
  },
  {
    "id":"ba100000-0003-0001-0000-000000000000","module_id":"ba100000-0003-0000-0000-000000000000",
    "title":"Exchange Rates and International Trade","order_index":1,"xp_reward":50,"estimated_minutes":8,"is_published":True,
    "content":[
      {"type":"intro","emoji":"🌍","heading":"Exchange Rates and International Trade","body":"Exchange rates determine the relative price of one currency in terms of another. Comparative advantage explains the basis for international trade."},
      {"type":"explanation","heading":"Exchange Rate Systems","body":"Countries choose different systems for managing their exchange rates.","key_terms":[{"term":"Floating exchange rate","definition":"Determined by supply and demand. No government intervention (e.g. GBP, USD, EUR)."},{"term":"Fixed exchange rate","definition":"Government pegs currency to another currency; requires intervention to maintain."},{"term":"Appreciation","definition":"Home currency buys more foreign currency."},{"term":"Depreciation","definition":"Home currency buys less foreign currency."}]},
      {"type":"worked_example","heading":"Effects of Sterling Depreciation","steps":["GBP depreciates from £1 = $1.50 to £1 = $1.20.","UK exports: become cheaper for US buyers — export volumes rise.","UK imports: foreign goods cost more in GBP — inflation rises, import volumes fall.","J-curve effect: Current account initially worsens (contracts fixed) before improving as volumes adjust."]},
      {"type":"explanation","heading":"Comparative Advantage","body":"Even if one country is absolutely better at producing everything, trade is still beneficial if each country specialises in what it produces at a lower opportunity cost.","key_terms":[{"term":"Absolute advantage","definition":"Producing a good with fewer resources than another country."},{"term":"Comparative advantage","definition":"Producing a good at a lower opportunity cost than another country."},{"term":"Opportunity cost","definition":"The next best alternative foregone."}]},
      {"type":"table","heading":"Protectionist Measures","headers":["Measure","Mechanism","Effect"],"rows":[["Tariff","Tax on imported goods","Raises import prices; reduces import volumes"],["Import quota","Limit on quantity of imports","Restricts import volumes; may push up domestic prices"],["Subsidy","Government payment to home industry","Lowers domestic production cost; diverts trade"],["Embargo","Complete ban on imports","Total trade restriction"]]}
    ]
  },
]

for lesson in ba1_lessons:
    r = post("lessons", lesson)
    print(f"BA1 lesson '{lesson['title'][:45]}': {r}")

# ═══════════════════════════════════════════════════════════════════
# BA4 LESSONS
# ═══════════════════════════════════════════════════════════════════

ba4_lessons = [
  {
    "id":"ba400000-0001-0001-0000-000000000000","module_id":"ba400000-0001-0000-0000-000000000000",
    "title":"CIMA Fundamental Ethical Principles","order_index":1,"xp_reward":50,"estimated_minutes":8,"is_published":True,
    "content":[
      {"type":"intro","emoji":"🎓","heading":"CIMA Fundamental Ethical Principles","body":"CIMA members must uphold five fundamental ethical principles at all times. These are embedded in the CIMA Code of Ethics and aligned with the IESBA International Code of Ethics."},
      {"type":"table","heading":"The Five Fundamental Principles","headers":["Principle","Meaning","Example of breach"],"rows":[["Integrity","Be straightforward and honest in all professional and business relationships","Knowingly preparing misleading financial statements"],["Objectivity","Do not allow bias or undue influence to override professional judgement","Approving an expense claim from a close friend without scrutiny"],["Professional Competence and Due Care","Maintain knowledge and skill to provide competent professional service","Giving tax advice outside your area of expertise"],["Confidentiality","Do not disclose information acquired in a professional relationship without proper authority","Discussing client financial data at a social event"],["Professional Behaviour","Comply with relevant laws and avoid actions that discredit the profession","Submitting a misleading CV to obtain a job"]]},
      {"type":"explanation","heading":"Ethical Frameworks","body":"When facing an ethical dilemma, accountants can use several frameworks to analyse the situation.","key_terms":[{"term":"Consequentialism (Utilitarianism)","definition":"Judge an action by its outcomes; the right action produces the greatest good for the greatest number."},{"term":"Deontological ethics (Kantian)","definition":"Judge an action by whether it follows universal moral rules, regardless of outcome."},{"term":"Virtue ethics","definition":"Focus on the character of the person — would a person of good character do this?"},{"term":"CIMA Code of Ethics","definition":"Principle-based (not rules-based) — requires judgement, not just compliance."}]},
      {"type":"explanation","heading":"Threats and Safeguards","body":"The conceptual framework identifies threats to the fundamental principles and requires accountants to apply safeguards.","key_terms":[{"term":"Self-interest threat","definition":"Financial or other interest that could inappropriately influence judgement."},{"term":"Self-review threat","definition":"Reviewing your own previous work."},{"term":"Advocacy threat","definition":"Promoting a client's position to the extent that objectivity is compromised."},{"term":"Familiarity threat","definition":"Too close a relationship leading to undue sympathy."},{"term":"Intimidation threat","definition":"Being deterred from acting objectively by actual or perceived threats."}]},
      {"type":"explanation","heading":"Safeguards Against Threats","body":"When a threat is identified, the accountant must determine whether it can be reduced to an acceptable level using available safeguards.","key_terms":[{"term":"Profession-level safeguards","definition":"CIMA Code, CPD requirements, professional standards, disciplinary procedures."},{"term":"Firm-level safeguards","definition":"Quality control systems, rotation policies, independent review."},{"term":"Resignation","definition":"If threats cannot be reduced to acceptable level, the accountant may need to withdraw."}]}
    ]
  },
  {
    "id":"ba400000-0001-0002-0000-000000000000","module_id":"ba400000-0001-0000-0000-000000000000",
    "title":"Ethical Conflicts and Whistleblowing","order_index":2,"xp_reward":50,"estimated_minutes":8,"is_published":True,
    "content":[
      {"type":"intro","emoji":"🔔","heading":"Ethical Conflicts and Whistleblowing","body":"Finance professionals frequently face pressure to act unethically. Knowing how to resolve conflicts and when to report wrongdoing is a critical professional skill."},
      {"type":"explanation","heading":"Resolving Ethical Conflicts","body":"CIMA provides a structured approach to resolving ethical conflicts. Steps should be followed in order, escalating as necessary.","key_terms":[{"term":"Step 1","definition":"Gather relevant facts and identify the ethical issue."},{"term":"Step 2","definition":"Identify affected parties and their interests."},{"term":"Step 3","definition":"Consider the relevant ethical principles and professional standards."},{"term":"Step 4","definition":"Identify available courses of action and their consequences."},{"term":"Step 5","definition":"Consult with a colleague, superior, ethics helpline, or legal adviser."},{"term":"Step 6","definition":"Escalate internally — to line manager, finance director, audit committee."},{"term":"Step 7","definition":"If unresolved and serious enough, consider external reporting (whistleblowing)."}]},
      {"type":"explanation","heading":"Whistleblowing (Protected Disclosure)","body":"Whistleblowing means reporting suspected wrongdoing in the public interest. In the UK, the Public Interest Disclosure Act 1998 (PIDA) protects qualifying disclosures from unfair dismissal.","key_terms":[{"term":"Qualifying disclosure","definition":"Genuine belief that a criminal offence, legal obligation breach, health and safety risk, or miscarriage of justice is occurring."},{"term":"Good faith","definition":"Disclosure must be in the public interest, not for personal gain."},{"term":"Internal disclosure","definition":"To employer — preferred route."},{"term":"Prescribed person disclosure","definition":"To a regulator (e.g. FCA, HMRC)."},{"term":"Public disclosure","definition":"To media — only allowed in specific narrow circumstances; higher threshold."}]},
      {"type":"explanation","heading":"Pressure from Management","body":"Accountants may face pressure to massage figures or sign off on inaccurate reports. Appropriate responses depend on severity.","key_terms":[{"term":"Document everything","definition":"Keep a clear written record of instructions and conversations."},{"term":"Refuse","definition":"Declining to do something unethical is always an option."},{"term":"Seek advice","definition":"CIMA ethics helpline, solicitor."},{"term":"Resign","definition":"If the organisation's culture is fundamentally unethical."}]}
    ]
  },
  {
    "id":"ba400000-0002-0001-0000-000000000000","module_id":"ba400000-0002-0000-0000-000000000000",
    "title":"Corporate Governance Frameworks","order_index":1,"xp_reward":50,"estimated_minutes":8,"is_published":True,
    "content":[
      {"type":"intro","emoji":"🏛️","heading":"Corporate Governance Frameworks","body":"Corporate governance refers to the system by which organisations are directed and controlled. It addresses the relationship between shareholders, directors, and other stakeholders."},
      {"type":"explanation","heading":"The Agency Problem","body":"The separation of ownership (shareholders) from control (directors) creates an agency problem. Directors may pursue their own interests rather than maximising shareholder wealth.","key_terms":[{"term":"Principal","definition":"The party on whose behalf the agent acts (shareholders)."},{"term":"Agent","definition":"The party acting on behalf of the principal (directors/managers)."},{"term":"Agency costs","definition":"Costs of monitoring agents and resolving conflicts (e.g. audit fees, incentive schemes)."},{"term":"Agency problem","definition":"Directors may prioritise personal gain over shareholder value."}]},
      {"type":"explanation","heading":"The UK Corporate Governance Code","body":"Applies to UK premium listed companies on a comply or explain basis. Sets out principles across five sections.","key_terms":[{"term":"Comply or explain","definition":"Companies must comply with the Code or explain why they have not."},{"term":"Section 2 — Division of Responsibilities","definition":"Separate Chair and CEO roles; at least half the board should be independent NEDs."},{"term":"Section 4 — Audit, Risk and Internal Control","definition":"Audit committee, risk management, internal controls."},{"term":"Section 5 — Remuneration","definition":"Align executive pay with long-term performance."}]},
      {"type":"table","heading":"Executive Directors vs Non-Executive Directors (NEDs)","headers":["Feature","Executive Directors","Non-Executive Directors"],"rows":[["Role","Run the business day-to-day","Provide independent oversight and challenge"],["Employment","Full-time employees","Part-time; fixed-term contracts"],["Pay","Salary + bonus + share options","Fixed fee (no bonuses — preserves independence)"],["Independence","Not independent","Should be independent from management"],["Key contributions","Operational expertise","Scrutiny, strategy, risk, governance"],["Committee roles","Not on audit/remuneration committees","Typically chair/sit on key committees"]]},
      {"type":"explanation","heading":"The Role of the Audit Committee","body":"A key governance mechanism comprising independent NEDs. Oversees financial reporting, internal controls, and auditor relationships.","key_terms":[{"term":"Composition","definition":"At least three independent NEDs; for FTSE 350 at least one with recent financial experience."},{"term":"Responsibilities","definition":"Review financial statements, monitor internal controls, manage external auditor relationship, oversee internal audit."}]}
    ]
  },
  {
    "id":"ba400000-0002-0002-0000-000000000000","module_id":"ba400000-0002-0000-0000-000000000000",
    "title":"Internal Controls and Risk Management","order_index":2,"xp_reward":50,"estimated_minutes":8,"is_published":True,
    "content":[
      {"type":"intro","emoji":"🛡️","heading":"Internal Controls and Risk Management","body":"Internal controls are processes designed to provide reasonable assurance that an organisation achieves its objectives."},
      {"type":"explanation","heading":"Types of Internal Control","body":"Internal controls fall into two broad categories: preventive (stop errors/fraud occurring) and detective (identify errors/fraud after they occur).","key_terms":[{"term":"Preventive controls","definition":"Segregation of duties, authorisation limits, password controls, physical access restrictions."},{"term":"Detective controls","definition":"Bank reconciliations, internal audit, exception reports, variance analysis."},{"term":"Segregation of duties","definition":"No single individual controls all stages of a transaction."}]},
      {"type":"table","heading":"The Risk Management Process","headers":["Stage","Description","Example"],"rows":[["Risk Identification","Identify all potential threats to objectives","SWOT analysis, risk registers, scenario planning"],["Risk Assessment","Evaluate likelihood and impact of each risk","Risk matrix: probability x impact"],["Risk Response (4Ts)","Choose how to deal with each risk","Terminate, Transfer, Tolerate, Treat"],["Monitoring and Review","Continuously monitor risks and control effectiveness","KRI reporting, internal audit"]]},
      {"type":"explanation","heading":"The 4T Risk Responses","body":"Once risks are assessed, management must choose a response.","key_terms":[{"term":"Terminate (avoid)","definition":"Stop the activity that creates the risk entirely."},{"term":"Transfer","definition":"Pass the financial consequences to a third party (e.g. insurance, outsourcing)."},{"term":"Tolerate (accept)","definition":"Accept the risk because the cost of controlling it exceeds the benefit."},{"term":"Treat (reduce)","definition":"Implement controls to reduce likelihood and/or impact."}]},
      {"type":"explanation","heading":"Limitations of Internal Controls","body":"Even well-designed systems have inherent limitations. No system can provide absolute assurance.","key_terms":[{"term":"Human error","definition":"Mistakes can occur in applying controls."},{"term":"Collusion","definition":"Two or more individuals working together can override segregation of duties."},{"term":"Management override","definition":"Management can instruct staff to bypass controls."},{"term":"Cost-benefit","definition":"Only controls where benefit exceeds cost are implemented."}]}
    ]
  },
  {
    "id":"ba400000-0003-0001-0000-000000000000","module_id":"ba400000-0003-0000-0000-000000000000",
    "title":"Contract Law","order_index":1,"xp_reward":50,"estimated_minutes":8,"is_published":True,
    "content":[
      {"type":"intro","emoji":"📝","heading":"Contract Law","body":"A contract is a legally binding agreement between two or more parties. Understanding the essential elements of a valid contract and what happens when contracts are breached is fundamental to business law."},
      {"type":"explanation","heading":"Essential Elements of a Valid Contract","body":"For a contract to be legally enforceable, all six elements must be present.","key_terms":[{"term":"Offer","definition":"A definite proposal made by the offeror to the offeree, capable of acceptance."},{"term":"Acceptance","definition":"Unconditional agreement to all terms of the offer. A counter-offer is a rejection."},{"term":"Consideration","definition":"Something of value exchanged by each party. Not necessarily money."},{"term":"Intention to create legal relations","definition":"Both parties must intend the agreement to be legally binding."},{"term":"Capacity","definition":"Both parties must be legally capable of entering a contract."},{"term":"Legality","definition":"The purpose of the contract must be lawful."}]},
      {"type":"explanation","heading":"Offer vs Invitation to Treat","body":"An offer must be distinguished from an invitation to treat (ITT). Only an offer can be accepted to form a contract.","key_terms":[{"term":"Offer","definition":"A firm proposal that can immediately be accepted to form a contract."},{"term":"Invitation to treat","definition":"An invitation to make an offer — not binding (e.g. goods on a shop shelf, job advertisement)."},{"term":"Key case — Carlill v Carbolic Smoke Ball Co [1893]","definition":"An advertisement can be an offer if sufficiently specific."}]},
      {"type":"table","heading":"Vitiating Factors — Grounds for Avoiding a Contract","headers":["Vitiating factor","Meaning","Remedy"],"rows":[["Misrepresentation","False statement of fact that induced the other party to contract","Rescission and/or damages"],["Mistake","Both parties contract under a fundamental shared misunderstanding","Contract may be void"],["Duress","Contract entered under physical or economic threats","Contract voidable by the victim"],["Undue influence","One party exploits position of trust to pressure the other","Contract voidable"],["Illegality","Contract for an unlawful purpose","Contract void and unenforceable"]]},
      {"type":"explanation","heading":"Breach of Contract and Remedies","body":"A breach occurs when a party fails to perform their contractual obligations.","key_terms":[{"term":"Damages","definition":"Financial compensation for loss suffered. Aim to put the claimant in the position had the contract been performed."},{"term":"Specific performance","definition":"Court order requiring the breaching party to perform their obligations. Used for unique goods or land."},{"term":"Injunction","definition":"Court order preventing a party from doing something."},{"term":"Remoteness","definition":"Damages only recoverable if the loss was reasonably foreseeable at the time of contracting."}]}
    ]
  },
  {
    "id":"ba400000-0003-0002-0000-000000000000","module_id":"ba400000-0003-0000-0000-000000000000",
    "title":"Company Law and Employment Law","order_index":2,"xp_reward":50,"estimated_minutes":10,"is_published":True,
    "content":[
      {"type":"intro","emoji":"⚖️","heading":"Company Law and Employment Law","body":"UK company law (Companies Act 2006) governs how companies are formed, managed, and wound up. Employment law sets out the rights and obligations of employers and employees."},
      {"type":"explanation","heading":"Types of Company","body":"Companies in the UK can be formed in different ways, with different implications for liability.","key_terms":[{"term":"Private Limited Company (Ltd)","definition":"Shares cannot be publicly traded; shareholders have limited liability."},{"term":"Public Limited Company (plc)","definition":"Can offer shares to the public; minimum share capital of £50,000."},{"term":"Limited liability","definition":"Shareholders' personal assets are protected; maximum loss equals amount invested."},{"term":"Separate legal personality","definition":"A company is a legal person distinct from its shareholders (Salomon v Salomon [1897])."},{"term":"Lifting the veil","definition":"Courts will occasionally ignore separate personality where fraud or evasion is involved."}]},
      {"type":"explanation","heading":"Directors' Duties (Companies Act 2006, s.171-177)","body":"The Companies Act 2006 codifies seven duties of directors.","key_terms":[{"term":"s.171 — Act within powers","definition":"Follow the company's constitution and only use powers for their proper purpose."},{"term":"s.172 — Promote the success of the company","definition":"Act in good faith to promote long-term success for members (shareholders) as a whole."},{"term":"s.174 — Exercise reasonable care, skill and diligence","definition":"Objective AND subjective standard — whichever is higher."},{"term":"s.175 — Avoid conflicts of interest","definition":"Disclose and, where required, obtain approval for situations of potential conflict."}]},
      {"type":"table","heading":"Key Employment Law Rights","headers":["Right","Qualifying period","Key points"],"rows":[["Unfair dismissal","2 years","Employer must show fair reason and follow a fair process"],["Wrongful dismissal","None (day 1)","Breach of contract — damages equal net pay for notice period"],["Redundancy pay","2 years","Statutory minimum based on age, length of service, weekly pay"],["Discrimination protection","None (day 1)","Equality Act 2010: protected characteristics include age, sex, race, disability"],["National Minimum Wage","None (day 1)","All workers entitled; rates set annually"]]},
      {"type":"explanation","heading":"Fraud Awareness","body":"Finance professionals must understand fraud risk. The Fraud Act 2006 creates three main offences.","key_terms":[{"term":"Fraud by false representation","definition":"Dishonestly making a false representation (e.g. submitting a false invoice)."},{"term":"Fraud by abuse of position","definition":"Using a position of trust to make financial gain (e.g. accountant diverting company funds)."},{"term":"Bribery Act 2010","definition":"Makes it illegal to give or receive bribes; corporate offence if company fails to prevent bribery by associated persons."},{"term":"Money laundering","definition":"Concealing origins of criminal proceeds; accountants have reporting obligations under POCA 2002."}]}
    ]
  },
]

for lesson in ba4_lessons:
    r = post("lessons", lesson)
    print(f"BA4 lesson '{lesson['title'][:45]}': {r}")

# ═══════════════════════════════════════════════════════════════════
# BA1 QUESTIONS
# ═══════════════════════════════════════════════════════════════════

ba1_questions = [
  ("ba100000-0001-0001-0000-000000000001","ba100000-0001-0001-0000-000000000000","mcq",1,"A price BELOW equilibrium results in:","Excess demand — price rises to restore equilibrium",'["Excess supply — firms reduce prices","Excess demand — price rises to restore equilibrium","Equilibrium is maintained automatically","The demand curve shifts leftward"]',"Below equilibrium price, quantity demanded exceeds quantity supplied (shortage). Competition among buyers pushes price up until equilibrium is restored."),
  ("ba100000-0001-0001-0000-000000000002","ba100000-0001-0001-0000-000000000000","true_false",2,"A rise in the price of a substitute good will INCREASE the demand for a product.","True",None,"If a substitute becomes more expensive, consumers switch to the cheaper alternative, increasing its demand and shifting the demand curve to the right."),
  ("ba100000-0001-0001-0000-000000000003","ba100000-0001-0001-0000-000000000000","mcq",3,"Given Qd = 80 - 4P and Qs = 8 + 4P, what is the equilibrium price?","£9",'["£9","£8","£7","£10"]',"Set Qd = Qs: 80 - 4P = 8 + 4P. 72 = 8P. P = £9. Check: Qd = 44 = Qs. Confirmed."),
  ("ba100000-0001-0001-0000-000000000004","ba100000-0001-0001-0000-000000000000","mcq",4,"Which of the following would shift the supply curve to the RIGHT?","A technological improvement reducing production costs",'["An increase in raw material costs","Introduction of a new tax on the product","A technological improvement reducing production costs","A fall in the number of producers"]',"Lower production costs increase profitability, encouraging more supply at every price — shifting the supply curve rightward."),
  ("ba100000-0001-0002-0000-000000000001","ba100000-0001-0002-0000-000000000000","mcq",1,"A product has a PED of -2.5. If price is increased by 10%, total revenue will:","Decrease, because demand is elastic",'["Increase, because demand is inelastic","Decrease, because demand is elastic","Stay the same, because PED = -2.5","Increase, because PED is negative"]',"|PED| = 2.5 > 1, so demand is elastic. A 10% price rise causes a 25% fall in quantity. Revenue falls when demand is elastic."),
  ("ba100000-0001-0002-0000-000000000002","ba100000-0001-0002-0000-000000000000","mcq",2,"If price rises from £50 to £60 and quantity demanded falls from 400 to 360 units, what is the PED?","-0.5",'["-0.5","-2.0","-0.25","-4.0"]',"%changeQd = -10%. %changeP = +20%. PED = -10%/20% = -0.5. |PED| < 1 means inelastic."),
  ("ba100000-0001-0002-0000-000000000003","ba100000-0001-0002-0000-000000000000","true_false",3,"A luxury good has a YED greater than 1.","True",None,"Luxury goods are income elastic (YED > 1): as income rises, demand rises proportionally more. Examples: designer clothing, fine dining."),
  ("ba100000-0001-0002-0000-000000000004","ba100000-0001-0002-0000-000000000000","mcq",4,"Which factor is most likely to make supply INELASTIC in the short run?","Perishable or time-specific output",'["Abundant spare production capacity","Short production lead times","Perishable or time-specific output","Easy availability of substitute inputs"]',"Perishable goods cannot be stored and must be sold regardless of price — making supply inelastic. Spare capacity and short lead times increase elasticity."),
  ("ba100000-0001-0003-0000-000000000001","ba100000-0001-0003-0000-000000000000","mcq",1,"In perfect competition, a firm earns only normal profit in the long run because:","Free entry and exit eliminates supernormal profit",'["The government regulates prices","Free entry and exit eliminates supernormal profit","Firms collude to keep prices stable","Products are highly differentiated"]',"Supernormal profit attracts new entrants. Increased supply drives down price until only normal profit remains."),
  ("ba100000-0001-0003-0000-000000000002","ba100000-0001-0003-0000-000000000000","mcq",2,"A monopolist wishing to maximise profit will produce where:","Marginal revenue equals marginal cost",'["Price equals average cost","Marginal revenue equals marginal cost","Total revenue is maximised","Price equals marginal cost"]',"All profit-maximising firms produce where MR = MC, regardless of market structure."),
  ("ba100000-0001-0003-0000-000000000003","ba100000-0001-0003-0000-000000000000","true_false",3,"Price discrimination allows a monopolist to capture more consumer surplus.","True",None,"Price discrimination charges different prices based on willingness to pay, converting consumer surplus into producer surplus (profit)."),
  ("ba100000-0001-0003-0000-000000000004","ba100000-0001-0003-0000-000000000000","mcq",4,"Which market structure is characterised by a small number of large interdependent firms?","Oligopoly",'["Perfect competition","Monopolistic competition","Oligopoly","Monopsony"]',"Oligopoly features a small number of dominant firms. Interdependence means each firm's actions affect rivals, leading to strategic behaviour."),
  ("ba100000-0002-0001-0000-000000000001","ba100000-0002-0001-0000-000000000000","mcq",1,"Which formula correctly represents the expenditure approach to GDP?","GDP = C + I + G + (X - M)",'["GDP = C + S + G + (X - M)","GDP = C + I + G + (X - M)","GDP = W + P + R + I","GDP = C + I - G + (X + M)"]',"Expenditure approach: C (consumption) + I (investment) + G (government spending) + net exports (X - M). Imports are subtracted because they represent spending on foreign output."),
  ("ba100000-0002-0001-0000-000000000002","ba100000-0002-0001-0000-000000000000","mcq",2,"If the MPC is 0.75, what is the value of the Keynesian multiplier?","4",'["3","4","0.25","1.75"]',"Multiplier = 1 / (1 - MPC) = 1 / 0.25 = 4. A £1 billion increase in government spending increases national income by £4 billion."),
  ("ba100000-0002-0001-0000-000000000003","ba100000-0002-0001-0000-000000000000","true_false",3,"A recession is technically defined as two consecutive quarters of negative real GDP growth.","True",None,"This is the standard technical definition. It refers to REAL GDP growth (adjusted for inflation)."),
  ("ba100000-0002-0001-0000-000000000004","ba100000-0002-0001-0000-000000000000","mcq",4,"Which of the following is an INJECTION into the circular flow of income?","Investment spending by firms",'["Savings by households","Income tax paid to government","Imports of goods","Investment spending by firms"]',"Injections add money into the circular flow: Investment (I), Government spending (G), and Exports (X). Withdrawals: Savings (S), Taxation (T), Imports (M)."),
  ("ba100000-0002-0002-0000-000000000001","ba100000-0002-0002-0000-000000000000","mcq",1,"A sharp rise in world oil prices causing domestic inflation is an example of:","Cost-push inflation",'["Demand-pull inflation","Cost-push inflation","Hyperinflation","Structural inflation"]',"Rising input costs (oil, raw materials) push up production costs. These are passed on as higher prices — cost-push inflation."),
  ("ba100000-0002-0002-0000-000000000002","ba100000-0002-0002-0000-000000000000","mcq",2,"A worker who left their job to look for a better one is experiencing which type of unemployment?","Frictional unemployment",'["Structural unemployment","Cyclical unemployment","Frictional unemployment","Seasonal unemployment"]',"Frictional unemployment is temporary unemployment when moving between jobs. It exists even in a healthy economy and is part of the natural rate."),
  ("ba100000-0002-0002-0000-000000000003","ba100000-0002-0002-0000-000000000000","true_false",3,"Inflation benefits debtors at the expense of creditors.","True",None,"Inflation erodes the real value of money. Debtors repay loans with money worth less in real terms — a gain. Creditors receive back less in real terms — a loss."),
  ("ba100000-0002-0002-0000-000000000004","ba100000-0002-0002-0000-000000000000","mcq",4,"The long-run Phillips Curve is vertical because:","In the long run, inflation expectations adjust, eliminating the trade-off",'["Unemployment cannot be reduced below zero","In the long run, inflation expectations adjust, eliminating the trade-off","Governments always choose zero inflation","The central bank targets unemployment rather than inflation"]',"In the long run, workers and firms adjust their expectations. The economy returns to the natural rate regardless of the inflation rate."),
  ("ba100000-0002-0003-0000-000000000001","ba100000-0002-0003-0000-000000000000","mcq",1,"The Bank of England raises interest rates. This is an example of:","Contractionary monetary policy",'["Expansionary fiscal policy","Contractionary monetary policy","Expansionary monetary policy","Contractionary fiscal policy"]',"Raising interest rates is contractionary monetary policy — controlled by the central bank, not the government."),
  ("ba100000-0002-0003-0000-000000000002","ba100000-0002-0003-0000-000000000000","mcq",2,"Which of the following is an AUTOMATIC STABILISER?","Unemployment benefits that rise during a recession",'["A new infrastructure project announced in the budget","Unemployment benefits that rise during a recession","The Bank of England cutting interest rates","A government decision to cut income tax"]',"Automatic stabilisers work without deliberate policy decisions. Unemployment benefits automatically rise during a recession, cushioning the fall in aggregate demand."),
  ("ba100000-0002-0003-0000-000000000003","ba100000-0002-0003-0000-000000000000","true_false",3,"Quantitative Easing involves the central bank creating new money to purchase financial assets.","True",None,"QE: the central bank electronically creates money and uses it to buy government bonds and other assets from financial institutions, increasing the money supply."),
  ("ba100000-0002-0003-0000-000000000004","ba100000-0002-0003-0000-000000000000","mcq",4,"Supply-side policies differ from demand-side policies in that they aim to:","Increase the productive capacity and long-run potential of the economy",'["Increase aggregate demand directly","Increase the productive capacity and long-run potential of the economy","Reduce the budget deficit in the short term","Control the money supply"]',"Supply-side policies shift the aggregate supply curve outward, increasing potential GDP and enabling non-inflationary growth."),
  ("ba100000-0003-0001-0000-000000000001","ba100000-0003-0001-0000-000000000000","mcq",1,"If sterling appreciates against the dollar, which of the following is most likely?","UK exports become more expensive for US buyers",'["UK exports become cheaper for US buyers","UK inflation rises due to higher import prices","UK exports become more expensive for US buyers","The current account deficit narrows"]',"Appreciation means £1 buys more dollars. A UK product priced at £100 now costs more dollars — making UK exports less competitive."),
  ("ba100000-0003-0001-0000-000000000002","ba100000-0003-0001-0000-000000000000","mcq",2,"Country A: 10 cars or 20 tonnes of wheat per day. Country B: 8 cars or 24 tonnes of wheat. Who has comparative advantage in wheat?","Country B — its opportunity cost of wheat is lower",'["Country A — it produces more cars","Country B — its opportunity cost of wheat is lower","Country A — it produces more wheat","Neither — comparative advantage only applies to absolute producers"]',"Country A: 1 tonne wheat costs 0.5 cars. Country B: 1 tonne wheat costs 0.33 cars. Country B has lower opportunity cost in wheat."),
  ("ba100000-0003-0001-0000-000000000003","ba100000-0003-0001-0000-000000000000","true_false",3,"The J-curve effect suggests that a currency depreciation initially worsens the current account before it improves.","True",None,"Initially, existing trade contracts mean import volumes do not fall immediately. Import costs rise in domestic currency, worsening the current account. Over time volumes adjust and the current account improves."),
  ("ba100000-0003-0001-0000-000000000004","ba100000-0003-0001-0000-000000000000","mcq",4,"A tariff on imported steel is an example of:","A protectionist measure to reduce import competition",'["A supply-side policy to boost productivity","A protectionist measure to reduce import competition","An automatic stabiliser","A monetary policy tool"]',"A tariff is a tax on imports that raises the price of imported goods, making domestic producers more competitive."),
]

for qid, lid, qtype, oi, prompt, answer, opts, expl in ba1_questions:
    data = {"id": qid, "lesson_id": lid, "question_type": qtype, "prompt": prompt,
            "correct_answer": answer, "order_index": oi, "explanation": expl}
    if opts:
        data["options"] = json.loads(opts)
    r = post("questions", data)
    status = "OK" if r == 201 else str(r)
    print(f"  BA1 Q {oi} ({lid[-8:]}): {status}")

# ═══════════════════════════════════════════════════════════════════
# BA4 QUESTIONS
# ═══════════════════════════════════════════════════════════════════

ba4_questions = [
  ("ba400000-0001-0001-0000-000000000001","ba400000-0001-0001-0000-000000000000","mcq",1,"A management accountant is asked to prepare a report that they know contains misleading information. Which fundamental principle is MOST directly threatened?","Integrity",'["Confidentiality","Professional Behaviour","Integrity","Objectivity"]',"Integrity requires being straightforward and honest. Knowingly preparing misleading information directly breaches integrity."),
  ("ba400000-0001-0001-0000-000000000002","ba400000-0001-0001-0000-000000000000","mcq",2,"An accountant has worked with the same client for 15 years and is close friends with the finance director. This creates which threat?","Familiarity threat",'["Self-interest threat","Advocacy threat","Intimidation threat","Familiarity threat"]',"Familiarity threat arises when a close relationship leads to over-sympathy, inadequate scrutiny, or prioritising the client's interests over professional obligations."),
  ("ba400000-0001-0001-0000-000000000003","ba400000-0001-0001-0000-000000000000","true_false",3,"The CIMA Code of Ethics is rules-based, requiring specific compliance with detailed rules for every situation.","False",None,"The CIMA Code of Ethics is PRINCIPLE-based, not rules-based. It requires members to exercise professional judgement in applying the fundamental principles."),
  ("ba400000-0001-0001-0000-000000000004","ba400000-0001-0001-0000-000000000000","mcq",4,"An accountant is reviewing financial statements that they themselves prepared last year. This is an example of:","Self-review threat",'["Self-interest threat","Self-review threat","Familiarity threat","Advocacy threat"]',"Self-review threat occurs when an accountant evaluates or audits their own previous work. Objectivity is compromised."),
  ("ba400000-0001-0002-0000-000000000001","ba400000-0001-0002-0000-000000000000","mcq",1,"Under UK law, a whistleblowing disclosure is MOST likely to receive legal protection if:","The employee believes in good faith it is in the public interest",'["It is made directly to the national press","The employee believes in good faith it is in the public interest","The employee has proof of the wrongdoing","It involves a minor regulatory breach"]',"The Public Interest Disclosure Act 1998 requires a genuine, good-faith belief that the disclosure is in the public interest. Proof is not required."),
  ("ba400000-0001-0002-0000-000000000002","ba400000-0001-0002-0000-000000000000","mcq",2,"What should an accountant do FIRST when facing a potential ethical conflict at work?","Gather the relevant facts and clearly identify the ethical issue",'["Immediately contact the external auditors","Gather the relevant facts and clearly identify the ethical issue","Resign to avoid being implicated","Report to the financial regulator"]',"The first step in CIMA's ethical conflict resolution framework is to gather facts and identify the nature of the ethical issue."),
  ("ba400000-0001-0002-0000-000000000003","ba400000-0001-0002-0000-000000000000","true_false",3,"An accountant who makes a protected disclosure can be legally dismissed by their employer for doing so.","False",None,"PIDA 1998 specifically protects whistleblowers from unfair dismissal and workplace detriment. Dismissing an employee for a qualifying protected disclosure is automatically unfair."),
  ("ba400000-0001-0002-0000-000000000004","ba400000-0001-0002-0000-000000000000","mcq",4,"An accountant's manager instructs them to overstate revenue to meet a bonus target. The most appropriate FIRST action is to:","Refuse and document the request; discuss the concern with the manager or seek guidance",'["Comply — the manager takes responsibility","Immediately report to the external auditor","Refuse and document the request; discuss the concern with the manager or seek guidance","Resign immediately"]',"The accountant should refuse, document the instruction, and attempt to resolve internally first. Immediately going external skips internal escalation steps."),
  ("ba400000-0002-0001-0000-000000000001","ba400000-0002-0001-0000-000000000000","mcq",1,"The agency problem in corporate governance arises from:","The separation of ownership from control, where managers may not act in shareholders' interests",'["External auditors acting in their own interest","The separation of ownership from control, where managers may not act in shareholders interests","Government regulation of company directors","Too many shareholders having conflicting objectives"]',"The agency problem arises because directors (agents) control the company on behalf of shareholders (principals). Directors may pursue personal benefits rather than maximising shareholder value."),
  ("ba400000-0002-0001-0000-000000000002","ba400000-0002-0001-0000-000000000000","mcq",2,"The UK Corporate Governance Code applies on a:","Comply or explain basis — companies must comply or give reasons why not",'["Mandatory compliance basis — all companies must follow it","Comply or explain basis — companies must comply or give reasons why not","Voluntary basis — companies can choose whether to follow it","Regulatory basis — enforced by the FCA with fines"]',"The UK Corporate Governance Code is not legally binding. Premium-listed companies must disclose whether they have complied, and if not, must explain their reasons."),
  ("ba400000-0002-0001-0000-000000000003","ba400000-0002-0001-0000-000000000000","true_false",3,"Executive directors should serve on the remuneration committee to ensure appropriate pay levels are set.","False",None,"Executive directors should NOT sit on the remuneration committee — they have a conflict of interest in setting their own pay. The committee must consist exclusively of independent NEDs."),
  ("ba400000-0002-0001-0000-000000000004","ba400000-0002-0001-0000-000000000000","mcq",4,"Which of the following best describes the purpose of the audit committee?","To oversee financial reporting, internal controls, and auditor relationships",'["To prepare the annual financial statements","To manage day-to-day financial operations","To oversee financial reporting, internal controls, and auditor relationships","To set the external auditors fees"]',"The audit committee oversees: integrity of financial statements, internal control and risk management systems, external auditor relationship, and internal audit function."),
  ("ba400000-0002-0002-0000-000000000001","ba400000-0002-0002-0000-000000000000","mcq",1,"A company purchases insurance for its warehoused stock against fire damage. This is an example of which risk response?","Transfer",'["Terminate","Tolerate","Transfer","Treat"]',"Insurance transfers the financial consequences of the risk to the insurer. The company still faces the risk of fire, but the financial impact is transferred."),
  ("ba400000-0002-0002-0000-000000000002","ba400000-0002-0002-0000-000000000000","mcq",2,"Requiring different employees to authorise purchases, receive goods, and approve payment is an example of:","Segregation of duties",'["Segregation of duties","Authorisation control","Physical control","Detective control"]',"Segregation of duties ensures no single person controls all stages of a transaction, making fraud much harder to commit and conceal."),
  ("ba400000-0002-0002-0000-000000000003","ba400000-0002-0002-0000-000000000000","true_false",3,"Internal controls can provide absolute assurance that an organisation will achieve its objectives.","False",None,"Internal controls can only provide REASONABLE assurance — not absolute. Limitations include human error, collusion, management override, and cost-benefit trade-offs."),
  ("ba400000-0002-0002-0000-000000000004","ba400000-0002-0002-0000-000000000000","mcq",4,"A bank reconciliation performed monthly is an example of which type of control?","Detective control",'["Preventive control","Detective control","Corrective control","Directive control"]',"Bank reconciliations detect errors and discrepancies after they have occurred. Preventive controls stop errors from occurring in the first place."),
  ("ba400000-0003-0001-0000-000000000001","ba400000-0003-0001-0000-000000000000","mcq",1,"Party A offers to sell goods for £1,000. Party B replies 'I'll take them for £900.' Which is correct?","Party B has made a counter-offer, rejecting A's original offer",'["A binding contract is formed at £900","Party B has made a counter-offer, rejecting As original offer","The original offer remains open for A to accept","Party B has made a valid acceptance with a modification"]',"A counter-offer is a rejection of the original offer and a new offer in its place. The original offer is destroyed."),
  ("ba400000-0003-0001-0000-000000000002","ba400000-0003-0001-0000-000000000000","mcq",2,"A product displayed on a supermarket shelf with a price label is:","An invitation to treat — not a binding offer",'["An offer that customers can accept at the checkout","An invitation to treat — not a binding offer","A guarantee of supply at that price","A contract formed when the customer picks up the item"]',"Goods on a shelf are an invitation to treat (Pharmaceutical Society of GB v Boots Cash Chemists [1953]). The customer makes the offer by presenting goods at the checkout."),
  ("ba400000-0003-0001-0000-000000000003","ba400000-0003-0001-0000-000000000000","true_false",3,"Consideration in a contract must always be money.","False",None,"Consideration is 'something of value' — but it does not have to be money. It can be goods, services, or a promise to do (or refrain from doing) something."),
  ("ba400000-0003-0001-0000-000000000004","ba400000-0003-0001-0000-000000000000","mcq",4,"Which remedy is most appropriate when a buyer breaches a contract for the sale of a unique, irreplaceable painting?","Specific performance — court orders the buyer to complete the purchase",'["Damages — financial compensation for loss","Specific performance — court orders the buyer to complete the purchase","Rescission — the contract is unwound","Injunction — prevents the seller from selling elsewhere"]',"Specific performance is available where damages would be an inadequate remedy — typically for unique goods (land, specific antiques, art)."),
  ("ba400000-0003-0002-0000-000000000001","ba400000-0003-0002-0000-000000000000","mcq",1,"The principle established in Salomon v Salomon [1897] states that:","A company is a legal person separate from its shareholders",'["Directors are personally liable for all company debts","A company is a legal person separate from its shareholders","Shareholders can always be sued for company obligations","Companies must have at least two shareholders"]',"Salomon v Salomon is the foundation of company law. Even a one-person company is a separate legal entity — it can own property, enter contracts, and be sued in its own name."),
  ("ba400000-0003-0002-0000-000000000002","ba400000-0003-0002-0000-000000000000","mcq",2,"Under the Companies Act 2006, a director must promote the success of the company for the benefit of:","The shareholders as a whole in the long term",'["The directors collectively","The shareholders as a whole in the long term","All stakeholders including employees, suppliers and creditors equally","The majority shareholder"]',"s.172 CA 2006 requires directors to act in good faith to promote long-term success for the benefit of members (shareholders) as a whole."),
  ("ba400000-0003-0002-0000-000000000003","ba400000-0003-0002-0000-000000000000","mcq",3,"An employee is dismissed without notice after 3 months. They have no unfair dismissal claim, but may have a claim for:","Wrongful dismissal",'["Redundancy pay","Wrongful dismissal","Discrimination under the Equality Act","Statutory maternity pay"]',"Unfair dismissal requires 2 years' service. Wrongful dismissal is a breach of contract claim available from day 1 — applies when employer fails to give proper notice."),
  ("ba400000-0003-0002-0000-000000000004","ba400000-0003-0002-0000-000000000000","mcq",4,"Under the Bribery Act 2010, which offence can a company commit even if the bribery was by a third party without the company's knowledge?","Failure to prevent bribery by an associated person",'["Fraud by false representation","Failure to prevent bribery by an associated person","Fraud by abuse of position","Money laundering"]',"The Bribery Act 2010 s.7 creates strict liability: a company is guilty if an associated person pays a bribe on its behalf, unless the company had adequate anti-bribery procedures."),
]

for qid, lid, qtype, oi, prompt, answer, opts, expl in ba4_questions:
    data = {"id": qid, "lesson_id": lid, "question_type": qtype, "prompt": prompt,
            "correct_answer": answer, "order_index": oi, "explanation": expl}
    if opts:
        data["options"] = json.loads(opts)
    r = post("questions", data)
    status = "OK" if r == 201 else str(r)
    print(f"  BA4 Q {oi} ({lid[-8:]}): {status}")

print("\nAll BA1 and BA4 done.")
