/**
 * Build-time script: reads NEXT_PUBLIC_API_URL and writes static/api-base.js.
 *
 * Vercel runs this via the buildCommand in vercel.json.
 * Locally: `node scripts/inject-config.js` (or just don't run it — the
 * default empty string means all fetch calls use relative paths, which is
 * what the FastAPI dev server expects).
 */
const fs   = require('fs');
const path = require('path');

const apiUrl = (process.env.NEXT_PUBLIC_API_URL || '').replace(/\/$/, '');

const js = `/* Auto-generated by scripts/inject-config.js — do not edit */
window.__MONTHENDIQ_API_BASE__ = ${JSON.stringify(apiUrl)};
`;

const out = path.join(__dirname, '..', 'static', 'api-base.js');
fs.writeFileSync(out, js, 'utf8');
console.log('[inject-config] wrote static/api-base.js  API_BASE =', apiUrl || '(empty — relative paths)');
